# This workflow builds a map using the base and branch commit of a PR and uploads
# the logs as an artifact that update-pr.yml uses to add back as a comment.

name: Performance

on:
  workflow_dispatch:

env:
  AREA: monaco
  RAM: 4g

jobs:
  performance:
    name: Performance Test
    runs-on: self-hosted
    timeout-minutes: 20
    continue-on-error: true
    container:
      image: ubuntu:22.04
    steps:
      - name: Install git
        run: |
          apt update
          apt install -y git
          git config --global --add safe.directory '*'
      - name: 'Checkout base'
        uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g strip-ansi-cli@3.0.2

      - name: 'Build'
        run: ./scripts/build.sh

      - name: 'Download data'
        shell: bash
        run: |
          set -eo pipefail
          cp planetiler-dist/target/*with-deps.jar run.jar && java -jar run.jar --only-download --area="${{ env.AREA }}"

      - name: 'Run'
        run: |
          rm -rf data/out.mbtiles data/tmp
          cp planetiler-dist/target/*with-deps.jar run.jar
          java -Xms${{ env.RAM }} -Xmx${{ env.RAM }} -jar run.jar --area="${{ env.AREA }}" --mbtiles=data/out.mbtiles 2>&1 | tee log
          ls -alh run.jar | tee -a log
          cat log | strip-ansi > log.txt

      - name: 'Upload build-info'
        uses: actions/upload-artifact@v3
        with:
          path: ./log.txt
